// ============================================================
// GEMPAR v2.1 — Supabase Browser Client
// Untuk: Client Components, Hooks, Zustand Store
// ============================================================

import { createBrowserClient } from '@supabase/ssr';
import { Database } from './database.types'; // Generated by supabase gen types

let browserClient: ReturnType<typeof createBrowserClient<Database>> | null = null;

/**
 * Get or create Supabase browser client (singleton).
 * Use in Client Components and hooks.
 * 
 * @example
 * const supabase = getSupabaseBrowser();
 * const { data } = await supabase.from('anggota').select('*');
 */
export function getSupabaseBrowser() {
  if (browserClient) return browserClient;

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error(
      'Missing Supabase environment variables. ' +
      'Check NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.'
    );
  }

  browserClient = createBrowserClient<Database>(supabaseUrl, supabaseKey, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
  });

  return browserClient;
}

/**
 * Hook-friendly alias for browser client.
 */
export const supabaseBrowser = getSupabaseBrowser;
